name: Security CI

on:
  push:
  pull_request:

jobs:
  test-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies (include security tools)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install safety bandit

      - name: Run unit tests
        run: |
          pytest -q

      # Let scans complete even if they find issues so the job reaches the end
      - name: Safety vulnerability scan (requirements.txt)
        continue-on-error: true
        run: |
          safety check --full-report --file=requirements.txt

      - name: Bandit security scan (source code)
        continue-on-error: true
        run: |
          bandit -q -r .

      - name: Summarize findings
        run: echo "Scans complete. Review logs in each step."
